---

- hosts: xmrig
  remote_user: root
  tasks:
    - name: Upgrade OS
      apt:
        update_cache: true
        upgrade: true
    - name: Install dependencies
      apt: 
        name: "ca-certificates"
        state: present
    - name: Create xmrig directory
      file:
        path: /opt/xmrig
        state: directory
    - name: Download xmrig
      get_url:
        url: https://github.com/xmrig/xmrig/releases/download/v{{ xmrigVersion }}/xmrig-{{ xmrigVersion }}-xenial-x64.tar.gz
        dest: /opt/xmrig/xmrig.tar.gz
        mode: 0644
    - name: Extract miner
      unarchive:
        src: /opt/xmrig/xmrig.tar.gz
        dest: /opt/xmrig
        extra_opts: [--strip-components=1]
    - name: Create service file
      template:
        src: templates/xmrig.service
        dest: /etc/systemd/system/xmrig.service
        mode: 0644
    - name: Enable and start service
      systemd:
        name: xmrig
        state: started
        enabled: true
        masked: no